HAPPY = [
    ['heat waves-glass animals', 'a vibe song'],
    ['Girlfriend-Charlie Puth', 'a cheerful melody'],
    ['India Waale', 'a groovy & energetic song'],
    ['Dwapara- Krishnam Pranaya', 'a feelgood melody'],
    ['Nanage Neenu', 'a melody'],
    ['Chaleya', 'a groovy beat'],
    ['guruvara sanje song', 'a groovy melody'],
    ['Chuttamalle', 'a melodious track'],
    ['Aasa Kooda', 'a song to vibe'],
    ['Jeena Jeena Ya', 'a groovy song to dance'],
    ['Arabic Kuthu - Halamithi Habibo', 'a catchy song'],
    ['Enjoy Enjaami', 'a catchy track'],
    ['Illuminati - From Aavesham', 'an energetic party track'],
    ['Maate Vinadhuga', 'a vibey melody'],
    ['Buttabomma - Telugu', 'a playful track'],
    ['I Like Me Better', 'a vibe song'],
    ['Señorita', 'a catchy song'],
    ['The Nights', 'a vibe song'],
    ['Manasilaayo', 'a dance number'],
    ['Bhool Bhulaivaa 2 Title', 'a catchy dance number'],
    ['Tauba Tauba (From Bad Newz)', 'a groovy beat'],
    ['Peaches (feat. Daniel Caesar)', 'a vibe song'],
    ['Astronaut In The Ocean-Arem Ozguc', 'a groovy track'],
    ['positions', 'a vibe song'],
    ['We Don\'t Talk Anymore', 'a catchy song'],
    ['Don\'t Worry', 'a vibe track'],
    ['I Wanna Be Yours', 'a vibe song'],
    ['Nashe Si Chadh Gayi', 'a dance number'],
    ['Sanam', 'a melody'],
    ['Rowdy Baby', 'a song to dance'],
    ['Taki Taki (feat. Selena Gomez)', 'a popular song'],
    ['Stereo Hearts (feat. Adam Levine)', 'a feelgood catchy song']
]


CALM = [
    ['yeh sham mastani', 'an old hit'],
    ['Mayavi', 'a song to vibe'],
    ['Ninna Gungalli', 'a calm song to vibe'],
    ['srivali', 'a sweet melody'],
    ['Zara Zara - lofi', 'a calm song lofi'],
    ['Baani Gondu Elle', 'an old hit'],
    ['Let me down slowly', 'a calm song to vibe'],
    ['samajavaragamana', 'a calm melody'],
    ['Munjaane Manjali', 'a song to vibe'],
    ['Nee Sannihake Bandre', 'a calm melody'],
    ['Minchagi Neenu', 'a calm melody'],
    ['Neele Neele Ambar Par Male Version', 'an old hit'],
    ['Tum itna jo muskura rahe ho arth - live', 'an old hit'],
    ['Ninna Danigaagi', 'a calming song to vibe'],
    ['Hallu jenu', 'an old hit'],
    ['Ninna Ninna Snehake', 'an old hit'],
    ['Jab Tak', 'a song to vibe'],
    ['Janam Janam', 'a song to vibe'],
    ['Tere Liye', 'an old hit'],
    ['O Mere Dil Ke Chain', 'an old hit'],
    ['Agar Tum Mil Jao', 'an old hit'],
    ['Tu Hi Meri Shab Hai', 'an old hit']
]


ANGER = [
    ['Krishna Flute', 'a calm instrumental'],
    ['Shree Hari Stotram', 'a calming divine chant'],
    ['Ram Siya Ram', 'a divine song'],
    ['Nilavinte Neelabhasma', 'a calming track'],
    ['Krishna Krish Flute', 'a calm instrumental'],
    ['Two Thousand and Seventeen', 'a relaxing instrumental'],
    ['Sojugada Soojumallige', 'a calming song'],
    ['Raga Bagesri', 'classical music'],
    ['Shiva Tandava stotram', 'a divine chant'],
    ['Kaathalae Kaathalae', 'a calming song'],
    ['Beach Calmness', 'ambient sounds'],
    ['Mori painjainiya', 'classical music'],
    ['Rut Badle', 'classical music'],
    ['Sapta Sagaradaache', 'a calming song'],
    ['Clair de Lune', 'an instrumental'],
    ['Main Nashe Mein Hoon', 'a ghazal'],
    ['Su Wu Tending Sheep', 'a calm instrumental'],
    ['We Can Fly', 'a calm instrumental'],
    ['Le Francaise', 'ambient sounds'],
    ['Weightless', 'ambient sounds']
]

SAD = [
    ['Yenagali', 'a motivational melody'],
    ['Olithu Maadu Manusa-C Ashwath', 'a motivational melody'],
    ['Happy-allok', 'a motivational track'],
    ['Kaun Tujhe', 'a feeling song s'],
    ['Preethisuve', 'a romantic track s'],
    ['Badri Ki Dulhania', 'an energetic beat to cheer you up!'],
    ['Tum Hi Ho', 'a romantic track s'],
    ['Why This Kolaveri Di', 'a playful track'],
    ['Agar Tum Saath Ho', 'a feeling song s'],
    ['Roja Jaaneman', 'a feeling song s'],
    ['Idhu Yaaru Bareda Katheya', 'a self-reflective track s'],
    ['Kadalanu', 'a calm track'],
    ['Tujh Mein Rab Dikhta Hai', 'a romantic melody s'],
    ['Kanave Unai', 'a feeling song s'],
    ['Nee Thoreda Ghaligeyali', 'a feeling song s'],
    ['Mosa Madalendu Neenu', 'a feeling song s'],
]


SURPRISE = [
    ['Starboy', 'a catchy pop song'],
    ['Dangerous-Michael Jackson', 'a pop hit!'],
    ['Muqabla', 'a catchy beat'],
    ['Gangnam Style', 'a groovy track'],
    ['Aaj Ki Raat', 'a dance number!'],
    ['Oo Antava Telugu', 'a dance number!'],
    ['Darshana-From Hridayam', 'a song to vibe'],
    ['Belageddu-kirik party', 'a catchy melody'],
    ['Chammak Challo', 'a catchy dance number!'],
    ['Shape of You', 'a catchy song'],
    ['Bang Bang', 'a groovy bollywood song'],
    ['Dhan Te Nan', 'a catchy song'],
    ['Sunn Raha Hai', 'a melody'],
    ['Thunder', 'Imagine Dragons', 'catchy'],
    ['Skyfall', 'a song to vibe'],
    ['I Ain\'t Worried-Imagine Dragons', 'a playful song'],
    ['Believer', 'an energetic track'],
    ['Billie Jean', 'a pop hit!'],
    ['Don\'t Copy My Flow', 'a song to vibe'],
    ['Hukum-Thalaivar Alappar', 'a massy track'],
    ['Oyaayiye Yaayiye', 'a melody'],
    ['Apsara Aali', 'a marathi classic'],
    ['Ugramm Veeram', 'a massy track'],
    ['eye of the tiger-survivor','a surprise track'],
    ['Ghosts-Michael Jackson', 'a micheal jackson hit'],
    ['They Don\'t Really Care About Us-Michael', 'a song from the king of pop'],
    ['Bad 2012-Michael Jackson', 'a pop superhit!'],
    ['Santhoshakke', 'a groovy song'],
    ['Tum Tum', 'a catchy song'],
    ['Blue Eyes', 'a catchy track'],
    ['Dham Powere', 'a pumped up mass track!'],
    ['Tagaru Banthu Tagaru', 'a massy track'],
    ['Feeling Good', 'a song to vibe'],
    ['Cult', 'a song filled with rage!'],
    ['Badukina Bannave', 'a melody'],
    ['Balma', 'a classical fusion'],
    ['Police Theme-Tagaru', 'a pumped up mass track!'],
    ['Huttidare Kannada', 'an old hit'],
    ['Surviva', 'a massy track'],
    ['Mental Ho Jawa-Tagaru', 'a dance number!'],
    ['Family Affair', 'a vibe song'],
    ['Safari', 'a catchy track'],
    ['Parichayavade', 'a melody']
]
